name: Build, Test, and Deploy Flask App on EC2 Instance using GitHub Actions 

on:
  push:
    branches:
      - main  # Run the action when code is pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest

      - name: Create SSH key file
        run: sudo echo "${{ secrets.EC2_SSH_KEY }}" > /tmp/id_rsa

      - name: Set permissions for SSH key
        run: sudo chmod 600 /tmp/id_rsa
      - name: Verify SSH Key File
        run:  cat /tmp/id_rsa

      - name: Deploy to EC2 
        env: 
          FLASK_APP_PATH: ${{ secrets.FLASK_APP_PATH }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          rsync -avz -e "ssh -v -i /tmp/id_rsa -o StrictHostKeyChecking=no" ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.FLASK_APP_PATH }}
          ssh -i /tmp/id_rsa -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ${{ secrets.FLASK_APP_PATH }}
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart app.service
          EOF
    
